WebBanHang/ViewComponents/LoaiSpMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebBanHang.Models;

namespace WebBanHang.ViewComponents
{
    public class LoaiSpMenuViewComponent:ViewComponent
    {
        private readonly WebDbContext _context;
        public LoaiSpMenuViewComponent(WebDbContext context)
        {
            this._context = context;
        }


        public IViewComponentResult Invoke()
        {
            var listloaisp = _context.Categories.ToList();
            return View(listloaisp);
        }
    }
}

WebBanHang/Areas/Customer/Views/Shared/PartialSanPham.cshtml
@model Product
@using Newtonsoft.Json;
@{
    string[] listImg = Model.Images != null
        ? JsonConvert.DeserializeObject<string[]>(Model.Images)
        : new string[] { "no_img.png" };

    var firstImg = listImg[0];
}

<div class="col-lg-3 col-md-4 col-sm-6 mix oranges fresh-meat">
    <div class="featured__item">
        <div class="featured__item__pic set-bg" data-setbg="@Url.Content("../ProductsImages/Images/" + firstImg)"
            <ul class="featured__item__pic__hover">
                <li><a href="#"><i class="fa fa-heart"></i></a></li>
                <li><a href="#"><i class="fa fa-retweet"></i></a></li>
                <li><a href="#"><i class="fa fa-shopping-cart"></i></a></li>
            </ul>
        </div>
        <div class="featured__item__text">
            <h6><a asp-controller="Home" asp-action="ChiTietSanPham" asp-route-masp="@Model.Id">@Model.Name</a></h6>
            <h5>@Model.Price</h5>
        </div>
    </div>
</div>

WebBanHang/Areas/Customer/Views/Shared/_Layout.cshtml
@using WebBanHang.Models
@using WebBanHang.Helpers;
@inject WebDbContext _context
@using Newtonsoft.Json
@using WebBanHang.Helpers;
@{
	int? userId = SessionHelpers.GetUserId(Context);
	AppUser appUser = null;
	if (userId != null)
	{
		appUser = _context.AppUsers.FirstOrDefault(x => x.Id == userId);
	}
}
<!DOCTYPE html>
<html lang="zxx">

<head>
	<meta charset="UTF-8">
	<meta name="description" content="Ogani Template">
	<meta name="keywords" content="Ogani, unica, creative, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Ogani | Template</title>

	<!-- Google Font -->
	<link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

	<!-- Css Styles -->
	<link rel="stylesheet" href="../MyLib2/css/bootstrap.min.css" type="text/css">
	<link rel="stylesheet" href="../MyLib2/css/font-awesome.min.css" type="text/css">
	<link rel="stylesheet" href="../MyLib2/css/elegant-icons.css" type="text/css">
	<link rel="stylesheet" href="../MyLib2/css/nice-select.css" type="text/css">
	<link rel="stylesheet" href="../MyLib2/css/jquery-ui.min.css" type="text/css">
	<link rel="stylesheet" href="../MyLib2/css/owl.carousel.min.css" type="text/css">
	<link rel="stylesheet" href="../MyLib2/css/slicknav.min.css" type="text/css">
	<link rel="stylesheet" href="../MyLib2/css/style.css" type="text/css">
</head>

<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Humberger Begin -->
	<div class="humberger__menu__overlay"></div>
	<div class="humberger__menu__wrapper">
		<div class="humberger__menu__logo">
			<a href="#"><img src="../MyLib2/img/logo.png" alt=""></a>
		</div>
		<div class="humberger__menu__cart">
			<ul>
				<li><a href="#"><i class="fa fa-heart"></i> <span>1</span></a></li>
				<li><a href="#"><i class="fa fa-shopping-bag"></i> <span>3</span></a></li>
			</ul>
			<div class="header__cart__price">item: <span>$150.00</span></div>
		</div>
		<div class="humberger__menu__widget">
			<div class="header__top__right__language">
				<img src="../MyLib2/img/language.png" alt="">
				<div>English</div>
				<span class="arrow_carrot-down"></span>
				<ul>
					<li><a href="#">Spanis</a></li>
					<li><a href="#">English</a></li>
				</ul>
			</div>
			<div class="header__top__right__auth">
				@if (appUser == null)
				{
					<a asp-controller="Account" asp-action="Login"><i class="fa fa-user"></i>Đăng nhập</a>
				}
				else
				{
					<a asp-controller="Account" asp-action="Logout"><i class="fa fa-user"></i>Đăng xuất</a>
				}
			</div>
		</div>
		<nav class="humberger__menu__nav mobile-menu">
			<ul>
				<li class="active"><a href="./index.html">Home</a></li>
				<li><a href="./shop-grid.html">Shop</a></li>
				<li>
					<a href="#">Pages</a>
					<ul class="header__menu__dropdown">
						<li><a href="./shop-details.html">Shop Details</a></li>
						<li><a href="./shoping-cart.html">Shoping Cart</a></li>
						<li><a href="./checkout.html">Check Out</a></li>
						<li><a href="./blog-details.html">Blog Details</a></li>
					</ul>
				</li>
				<li><a href="./blog.html">Blog</a></li>
				<li><a href="./contact.html">Contact</a></li>
			</ul>
		</nav>
		<div id="mobile-menu-wrap"></div>
		<div class="header__top__right__social">
			<a href="#"><i class="fa fa-facebook"></i></a>
			<a href="#"><i class="fa fa-twitter"></i></a>
			<a href="#"><i class="fa fa-linkedin"></i></a>
			<a href="#"><i class="fa fa-pinterest-p"></i></a>
		</div>
		<div class="humberger__menu__contact">
			<ul>
				<li><i class="fa fa-envelope"></i> hello@colorlib.com</li>
				<li>Free Shipping for all Order of $99</li>
			</ul>
		</div>
	</div>
	<!-- Humberger End -->
	<!-- Header Section Begin -->
	<header class="header">
		<div class="header__top">
			<div class="container">
				<div class="row">
					<div class="col-lg-6 col-md-6">
						<div class="header__top__left">
							<ul>
								<li><i class="fa fa-envelope"></i> hello@colorlib.com</li>
								<li>Free Shipping for all Order of $99</li>
							</ul>
						</div>
					</div>
					<div class="col-lg-6 col-md-6">
						<div class="header__top__right">
							<div class="header__top__right__social">
								<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-linkedin"></i></a>
								<a href="#"><i class="fa fa-pinterest-p"></i></a>
							</div>
							<div class="header__top__right__language">
								<img src="../MyLib2/img/language.png" alt="">
								<div>English</div>
								<span class="arrow_carrot-down"></span>
								<ul>
									<li><a href="#">Spanis</a></li>
									<li><a href="#">English</a></li>
								</ul>
							</div>
							<div class="header__top__right__auth">
								@if (appUser == null)
								{
									<a asp-controller="Account" asp-action="Login"><i class="fa fa-user"></i>Đăng nhập</a>
								}
								else
								{
									<a asp-controller="Account" asp-action="Logout"><i class="fa fa-user"></i>Đăng xuất</a>
								}
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<div class="col-lg-3">
					<div class="header__logo">
						<a href="./index.html"><img src="../MyLib2/img/logo.png" alt=""></a>
					</div>
				</div>
				<div class="col-lg-6">
					<nav class="header__menu">
						<ul>
							<li class="active"><a href="./index.html">Home</a></li>
							<li><a href="./shop-grid.html">Shop</a></li>
							<li>
								<a href="#">Pages</a>
								<ul class="header__menu__dropdown">
									<li><a href="./shop-details.html">Shop Details</a></li>
									<li><a href="./shoping-cart.html">Shoping Cart</a></li>
									<li><a href="./checkout.html">Check Out</a></li>
									<li><a href="./blog-details.html">Blog Details</a></li>
								</ul>
							</li>
							<li><a href="./blog.html">Blog</a></li>
							<li><a href="./contact.html">Contact</a></li>
						</ul>
					</nav>
				</div>
				<div class="col-lg-3">
					<div class="header__cart">
						<ul>
							<li><a href="#"><i class="fa fa-heart"></i> <span>1</span></a></li>
							<li><a href="#"><i class="fa fa-shopping-bag"></i> <span>3</span></a></li>
						</ul>
						<div class="header__cart__price">item: <span>$150.00</span></div>
					</div>
				</div>
			</div>
			<div class="humberger__open">
				<i class="fa fa-bars"></i>
			</div>
		</div>
	</header>
	<!-- Header Section End -->
	<!-- Hero Section Begin -->
	<section class="hero">
		<div class="container">
			<div class="row">
				@await Component.InvokeAsync("LoaiSpMenu")
			</div>
		</div>
	</section>
	<!-- Hero Section End -->
	<!-- Categories Section Begin -->
	<section class="categories">
		<div class="container">
			<div class="row">
				<div class="categories__slider owl-carousel">
					<div class="col-lg-3">
						<div class="categories__item set-bg" data-setbg="../MyLib2/img/categories/cat-1.jpg">
							<h5><a href="#">Fresh Fruit</a></h5>
						</div>
					</div>
					<div class="col-lg-3">
						<div class="categories__item set-bg" data-setbg="../MyLib2/img/categories/cat-2.jpg">
							<h5><a href="#">Dried Fruit</a></h5>
						</div>
					</div>
					<div class="col-lg-3">
						<div class="categories__item set-bg" data-setbg="../MyLib2/img/categories/cat-3.jpg">
							<h5><a href="#">Vegetables</a></h5>
						</div>
					</div>
					<div class="col-lg-3">
						<div class="categories__item set-bg" data-setbg="../MyLib2/img/categories/cat-4.jpg">
							<h5><a href="#">drink fruits</a></h5>
						</div>
					</div>
					<div class="col-lg-3">
						<div class="categories__item set-bg" data-setbg="../MyLib2/img/categories/cat-5.jpg">
							<h5><a href="#">drink fruits</a></h5>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Categories Section End -->
	<!-- Featured Section Begin -->
	<section class="featured spad" style="height: 200px;">

	</section>

	<div class="container">
		<div class="row" id="displayProducts">
			@RenderBody()
		</div>
	</div>

	<!-- Featured Section End -->
	<!-- Blog Section Begin -->
	<section class="from-blog spad">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="section-title from-blog__title">
						<h2>From The Blog</h2>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-4 col-md-4 col-sm-6">
					<div class="blog__item">
						<div class="blog__item__pic">
							<img src="../MyLib2/img/blog/blog-1.jpg" alt="">
						</div>
						<div class="blog__item__text">
							<ul>
								<li><i class="fa fa-calendar-o"></i> May 4,2019</li>
								<li><i class="fa fa-comment-o"></i> 5</li>
							</ul>
							<h5><a href="#">Cooking tips make cooking simple</a></h5>
							<p>Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat </p>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-6">
					<div class="blog__item">
						<div class="blog__item__pic">
							<img src="../MyLib2/img/blog/blog-2.jpg" alt="">
						</div>
						<div class="blog__item__text">
							<ul>
								<li><i class="fa fa-calendar-o"></i> May 4,2019</li>
								<li><i class="fa fa-comment-o"></i> 5</li>
							</ul>
							<h5><a href="#">6 ways to prepare breakfast for 30</a></h5>
							<p>Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat </p>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-6">
					<div class="blog__item">
						<div class="blog__item__pic">
							<img src="../MyLib2/img/blog/blog-3.jpg" alt="">
						</div>
						<div class="blog__item__text">
							<ul>
								<li><i class="fa fa-calendar-o"></i> May 4,2019</li>
								<li><i class="fa fa-comment-o"></i> 5</li>
							</ul>
							<h5><a href="#">Visit the clean farm in the US</a></h5>
							<p>Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat </p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Blog Section End -->
	<!-- Footer Section Begin -->
	<footer class="footer spad">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-6 col-sm-6">
					<div class="footer__about">
						<div class="footer__about__logo">
							<a href="./index.html"><img src="../MyLib2/img/logo.png" alt=""></a>
						</div>
						<ul>
							<li>Address: 60-49 Road 11378 New York</li>
							<li>Phone: +65 11.188.888</li>
							<li>Email: hello@colorlib.com</li>
						</ul>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 col-sm-6 offset-lg-1">
					<div class="footer__widget">
						<h6>Useful Links</h6>
						<ul>
							<li><a href="#">About Us</a></li>
							<li><a href="#">About Our Shop</a></li>
							<li><a href="#">Secure Shopping</a></li>
							<li><a href="#">Delivery infomation</a></li>
							<li><a href="#">Privacy Policy</a></li>
							<li><a href="#">Our Sitemap</a></li>
						</ul>
						<ul>
							<li><a href="#">Who We Are</a></li>
							<li><a href="#">Our Services</a></li>
							<li><a href="#">Projects</a></li>
							<li><a href="#">Contact</a></li>
							<li><a href="#">Innovation</a></li>
							<li><a href="#">Testimonials</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-4 col-md-12">
					<div class="footer__widget">
						<h6>Join Our Newsletter Now</h6>
						<p>Get E-mail updates about our latest shop and special offers.</p>
						<form action="#">
							<input type="text" placeholder="Enter your mail">
							<button type="submit" class="site-btn">Subscribe</button>
						</form>
						<div class="footer__widget__social">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-instagram"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-pinterest"></i></a>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-12">
					<div class="footer__copyright">
						<div class="footer__copyright__text">
							<p>
								<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
								Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
								<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							</p>
						</div>
						<div class="footer__copyright__payment"><img src="../MyLib2/img/payment-item.png" alt=""></div>
					</div>
				</div>
			</div>
		</div>
	</footer>
	<!-- Footer Section End -->
	<!-- Js Plugins -->
	<script src="../MyLib2/js/jquery-3.3.1.min.js"></script>
	<script src="../MyLib2/js/bootstrap.min.js"></script>
	<script src="../MyLib2/js/jquery.nice-select.min.js"></script>
	<script src="../MyLib2/js/jquery-ui.min.js"></script>
	<script src="../MyLib2/js/jquery.slicknav.js"></script>
	<script src="../MyLib2/js/mixitup.min.js"></script>
	<script src="../MyLib2/js/owl.carousel.min.js"></script>
	<script src="../MyLib2/js/main.js"></script>

</body>

</html>