WebBanHang/Areas/Admin/Controllers/AppUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using WebBanHang.Helpers;
using WebBanHang.Models;
using WebBanHang.Security;
using WebBanHang.ViewModel;

namespace WebBanHang.Areas.Admin.Controllers
{
	[Area("Admin")]
	[AdminAuthorizationFilter]
	[Route("admin/user")]
	public class AppUsersController : Controller
	{
		private readonly WebDbContext _context;

		public AppUsersController(WebDbContext context)
		{
			_context = context;
		}

		[HttpGet("")]
		public async Task<IActionResult> Index()
		{
			var webDbContext = _context.AppUsers.Include(a => a.Role);
			return View(await webDbContext.ToListAsync());
		}

        // GET: Admin/AppUsers/Details/5
        [HttpGet("details")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.AppUsers == null)
            {
                return NotFound();
            }

            var appUser = await _context.AppUsers
                .Include(a => a.Role)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (appUser == null)
            {
                return NotFound();
            }

            return View(appUser);
        }

        // GET: Admin/AppUsers/Create
        [HttpGet("create")]
		public IActionResult Create()
		{
			ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "RoleName");
			return View();
		}

        // POST: Admin/AppUsers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost("create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,UserName,Password,Email,PhoneNumber,RoleId")] CreateAppUserViewModel appUserViewModel)
        {
            if (ModelState.IsValid)
            {
                var checkUser = Utils.CheckTonTaiUserNameAndEmail(appUserViewModel.UserName, appUserViewModel.Email, _context);

                if (!checkUser)
                {
                    var appUser = new AppUser
                    {
                        Name = appUserViewModel.Name,
                        UserName = appUserViewModel.UserName,
                        Password = appUserViewModel.Password,
                        Email = appUserViewModel.Email,
                        PhoneNumber = appUserViewModel.PhoneNumber,
                        RoleId = appUserViewModel.RoleId,
                        IsLock = false
                    };
                    _context.Add(appUser);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Tên tài khoản hoặc email đã tồn tại.");
                    ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "RoleName", 1);
                    return View(appUserViewModel);
                }
            }

            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "RoleName", 1);
            return View(appUserViewModel);
        }


        // GET: Admin/AppUsers/Edit/5
        [HttpGet("Edit")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.AppUsers == null)
            {
                return NotFound();
            }

			var user = await _context.Products.FindAsync(id);
			if (user == null)
			{
				return NotFound();
			}
			return View(user);
		}

		// POST: Admin/Product/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost("edit")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Name,UserName,Password,PhoneNumber,IsLock,RoleId")] AppUser user)
		{
			if (id != user.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(user);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!AppUserExists(user.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(user);
		}

        [HttpGet("delete")]
        public async Task<IActionResult> Delete(int? id)
        {
            var user = await _context.AppUsers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }
            else
            {
                _context.AppUsers.Remove(user);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        private bool AppUserExists(int id)
        {
            return (_context.AppUsers?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebBanHang/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebBanHang.Models;
using WebBanHang.Security;

namespace WebBanHang.Areas.Admin.Controllers
{
	[Area("Admin")]
	[AdminAuthorizationFilter]
	[Route("admin/category")]
	public class CategoryController : Controller
	{
		private readonly WebDbContext _context;

		[TempData]
		public string Message { get; set; }

		public CategoryController(WebDbContext context)
		{
			_context = context;
		}

		[HttpGet("")]
		public async Task<IActionResult> Index()
		{
			return _context.Categories != null ?
						View(await _context.Categories.ToListAsync()) :
						Problem("Entity set 'WebDbContext.Categories'  is null.");
		}

		public async Task<IActionResult> Details(int? id)
		{
			if (id == null || _context.Categories == null)
			{
				return NotFound();
			}

			var category = await _context.Categories
				.FirstOrDefaultAsync(m => m.Id == id);
			if (category == null)
			{
				return NotFound();
			}

			return View(category);
		}

		[HttpGet("create")]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost("create")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,Name")] Category category)
		{
			if (ModelState.IsValid)
			{
				_context.Add(category);
				await _context.SaveChangesAsync();
				TempData["Message"] = "Thêm danh mục " + category.Name + " thành công";
				return RedirectToAction(nameof(Index));
			}
			return View(category);
		}

		[HttpGet("edit")]
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null || _context.Categories == null)
			{
				return NotFound();
			}

			var category = await _context.Categories.FindAsync(id);
			if (category == null)
			{
				return NotFound();
			}
			return View(category);
		}

		[HttpPost("edit")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Category category)
		{
			if (id != category.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(category);
					await _context.SaveChangesAsync();
					TempData["Message"] = "Cập nhật danh mục thành công";
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!CategoryExists(category.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(category);
		}

		[HttpGet("delete")]
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null || _context.Categories == null)
			{
				return NotFound();
			}

			var category = await _context.Categories
				.FirstOrDefaultAsync(m => m.Id == id);
			if (category == null)
			{
				return NotFound();
			}

			var listProduct = await _context.Products.FirstOrDefaultAsync(m => m.Id == category.Id);
			if (listProduct == null)
			{
				TempData["Message"] = "Xóa thành công danh mục " + category.Name;
				_context.Categories.Remove(category);
				await _context.SaveChangesAsync();
			}
			else
			{
				TempData["Message"] = "Không thể xóa vì có sản phẩm thuộc danh mục này";
			}
			return RedirectToAction(nameof(Index));
		}

		private bool CategoryExists(int id)
		{
			return (_context.Categories?.Any(e => e.Id == id)).GetValueOrDefault();
		}
	}
}

WebBanHang/Areas/Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebBanHang.Helpers;
using WebBanHang.Models;
using WebBanHang.Security;
using WebBanHang.ViewModel;

namespace WebBanHang.Areas.Admin.Controllers
{
	[Area("Admin")]
	[AdminAuthorizationFilter]
	[Route("admin/product")]
	public class ProductController : Controller
	{
		private readonly WebDbContext _context;

		public ProductController(WebDbContext context)
		{
			_context = context;
		}

		[HttpGet("")]
		public async Task<IActionResult> Index()
		{
			var webDbContext = _context.Products.Include(p => p.Category);
			return View(await webDbContext.ToListAsync());
		}

		// GET: Admin/Product/Details/5
		[HttpGet("details")]
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null || _context.Products == null)
			{
				return NotFound();
			}

			var product = await _context.Products
				.Include(p => p.Category)
				.FirstOrDefaultAsync(m => m.Id == id);
			if (product == null)
			{
				return NotFound();
			}

			return View(product);
		}

		[HttpGet("create")]
		public IActionResult Create()
		{
			ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
			return View();
		}

		[HttpPost("create")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,Name,Price,Quantity,Images,CategoryId")] Product product)
		{
			if (ModelState.IsValid)
			{
				_context.Add(product);
				await _context.SaveChangesAsync();
				TempData["Message"] = "Thêm sản phẩm " + product.Name + " thành công";
				return RedirectToAction(nameof(Index));
			}
			ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", product.CategoryId);
			return View(product);
		}



        [HttpGet("edit")]
        public async Task<IActionResult> Edit(int? id)
		{
			if (id == null || _context.Products == null)
			{
				return NotFound();
			}

			var product = await _context.Products.FindAsync(id);
			if (product == null)
			{
				return NotFound();
			}
			ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", product.CategoryId);
			return View(product);
		}

		// POST: Admin/Product/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost("edit")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Price,Quantity,Images,CategoryId")] Product product)
		{
			if (id != product.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(product);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!ProductExists(product.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", product.CategoryId);
			return View(product);
		}

		// GET: Admin/Product/Delete/5

		[HttpGet("delete")]
		public async Task<IActionResult> Delete(int? id)
		{
			if (_context.Products == null)
			{
				return Problem("Không có sản phẩm nào");
			}
			var product = await _context.Products.FindAsync(id);
			if (product != null)
			{
				_context.Products.Remove(product);
				TempData["Message"] = "Xóa sản phẩm " + product.Name + " thành công.";
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		// POST: Admin/Product/Delete/5
		/*[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
		}*/

		private bool ProductExists(int id)
		{
			return (_context.Products?.Any(e => e.Id == id)).GetValueOrDefault();
		}





        [HttpGet("uploadphoto")]
        public IActionResult UploadPhoto(int id)
        {
            var product = _context.Products.Where(e => e.Id == id)
                .FirstOrDefault();
            if (product == null)
            {
                return NotFound("Không có sản phẩm");
            }
            ViewData["product"] = product;
            return View(new UploadOneFile());
        }


        [HttpPost("uploadphoto"), ActionName("UploadPhoto")]
        public async Task<IActionResult> UploadPhotoAsync(int id, [Bind("FileUpload")] UploadOneFile f)
        {
            var product = _context.Products.Where(e => e.Id == id)
                .FirstOrDefault();

            if (product == null)
            {
                return NotFound("Không có sản phẩm");
            }

            ViewData["product"] = product;

            if (f != null)
            {
                // fileName random
                var fileName = Path.GetFileNameWithoutExtension(Path.GetRandomFileName())
                     + Path.GetExtension(f.FileUpload.FileName);
                var wwwRootPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", "products");
                var filePath = Path.Combine(wwwRootPath, fileName);

                using (var filestream = new FileStream(filePath, FileMode.Create))
                {
                    await f.FileUpload.CopyToAsync(filestream);
                }


				var imgs = Utils.AddPhotoForProduct(fileName, product.Images);
				product.Images = imgs;
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Edit), new { id = id });
        }



        [HttpDelete("deleteimage")]
        public IActionResult DeleteImage([FromBody] DeleteImageRequest request)
        {
            var product = _context.Products.FirstOrDefault(p => p.Id == request.ProductId);
            if (string.IsNullOrEmpty(request.FileName) || product == null)
            {
                return BadRequest("Có lỗi xảy ra.");
            }

            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", "products", request.FileName);

            if (System.IO.File.Exists(filePath))
            {
                System.IO.File.Delete(filePath);
            }

			product.Images=Utils.RemovePhotoForProduct(request.FileName, product.Images);
			_context.SaveChanges();
			
            return Ok(new { message = "Ảnh đã được xóa thành công." });
        }

		//bổ trợ xóa ảnh
        public class DeleteImageRequest
        {
            public string FileName { get; set; }
            public int ProductId { get; set; }
        }
    }
}

WebBanHang/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
@using WebBanHang.Models
@using WebBanHang.Helpers;
@inject WebDbContext _context
@using Newtonsoft.Json
@using WebBanHang.Helpers;

@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@{
    int? userId = SessionHelpers.GetUserId(Context);
    AppUser appUser = null;
    if (userId != null)
    {
        appUser = _context.AppUsers.FirstOrDefault(x => x.Id == userId);
    }
    var Message = TempData["Message"] as string;

}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Trang quản trị viên</title>
    <link rel="stylesheet" href="../../MyLib1/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="../../MyLib1/assets/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="../../MyLib1/assets/css/style.css">
    <link rel="shortcut icon" href="../../MyLib1/assets/images/favicon.ico" />
</head>
<body>
    <div class="container-scroller">
        <div class="row">
            @if (!string.IsNullOrEmpty(Message))
            {
                <h4 class="alert alert-danger">
                    @Message
                </h4>
            }
            <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
                <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
                    <a class="navbar-brand brand-logo" href="../../index.html"><img src="../../MyLib1/assets/images/logo.svg" alt="logo" /></a>
                    <a class="navbar-brand brand-logo-mini" href="../../index.html"><img src="../../MyLib1/assets/images/logo-mini.svg" alt="logo" /></a>
                </div>
                <div class="navbar-menu-wrapper d-flex align-items-stretch" style="padding-right:135px;">
                    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                        <span class="mdi mdi-menu"></span>
                    </button>
                    <ul class="navbar-nav navbar-nav-right">
                        <li class="nav-item nav-profile dropdown">

                            @if (appUser != null)
                            {
                                <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                                    Xin chào @appUser.Name
                                </a>
                            }
                            <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
                                <a class="dropdown-item" asp-action="Logout" asp-controller="Account">
                                    <i class="mdi mdi-logout me-2 text-primary">Đăng xuất</i>
                                </a>
                            </div>
                        </li>
                    </ul>
                    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                        <span class="mdi mdi-menu"></span>
                    </button>
                </div>
            </nav>
            <!-- partial -->
            <div class="container-fluid page-body-wrapper">
                <!-- partial:../../partials/_sidebar.html -->
                <nav class="sidebar sidebar-offcanvas" id="sidebar">
                    <ul class="nav">
                        <li class="nav-item nav-profile">
                            <a href="#" class="nav-link">
                                <div class="nav-profile-text d-flex flex-column">
                                    @if (appUser != null)
                                    {
                                        <span class="font-weight-bold mb-2">@appUser.Name</span>
                                    }
                                </div>
                                <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="AppUsers" asp-action="Index">
                                <span class="menu-title">Quản lý người dùng</span>
                                <i class="mdi mdi-home menu-icon"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-bs-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
                                <span class="menu-title">Quản lý sản phẩm</span>
                                <i class="menu-arrow"></i>
                                <i class="mdi mdi-crosshairs-gps menu-icon"></i>
                            </a>
                            <div class="collapse" id="ui-basic">
                                <ul class="nav flex-column sub-menu">
                                    <li class="nav-item"> <a class="nav-link" asp-area="Admin" asp-controller="Product" asp-action="Index">Danh sách sản phẩm</a></li>
                                    <li class="nav-item"> <a class="nav-link" asp-area="Admin" asp-controller="Category" asp-action="Index">Danh mục sản phẩm</a></li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </nav>
                <!-- partial -->
                <div class="main-panel">
                    <div class="content-wrapper">
                        @RenderBody()
                    </div>

                    <footer class="footer">
                        <div class="container-fluid d-flex justify-content-between">
                            <span class="text-muted d-block text-center text-sm-start d-sm-inline-block">Thi thực hành</span>
                        </div>
                    </footer>
                </div>
            </div>
        </div>
    </div>

    <script src="../../MyLib1/assets/vendors/js/vendor.bundle.base.js"></script>

    <script src="../../MyLib1/assets/js/off-canvas.js"></script>
    <script src="../../MyLib1/assets/js/hoverable-collapse.js"></script>
    <script src="../../MyLib1/assets/js/misc.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>